
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),username text UNIQUE NOT NULL,name text NOT NULL,role text NOT NULL CHECK(role IN('Admin','Dispatcher','Driver','Accounting')),password_hash text NOT NULL);
CREATE TABLE IF NOT EXISTS customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company text NOT NULL,vat_id text,address text,city text,email text,phone text);
CREATE TABLE IF NOT EXISTS vehicles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,plate text UNIQUE NOT NULL,active boolean DEFAULT true);
CREATE TABLE IF NOT EXISTS trips(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),trip_number text UNIQUE NOT NULL,customer_id uuid REFERENCES customers(id),weight_kg numeric NOT NULL CHECK(weight_kg>=0 AND weight_kg<=1000),pieces integer DEFAULT 1,status text DEFAULT 'Planned',driver_id uuid REFERENCES users(id),vehicle_id uuid REFERENCES vehicles(id),route text,notes text,current_lat numeric,current_lng numeric,signature_data text,signature_at timestamptz,delivery_photo text,price_net numeric DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS trip_stops(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),trip_id uuid REFERENCES trips(id) ON DELETE CASCADE,stop_order integer NOT NULL,address text NOT NULL,customer_name text,planned_time timestamptz,delivered_at timestamptz);
CREATE TABLE IF NOT EXISTS gps_points(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),trip_id uuid REFERENCES trips(id) ON DELETE CASCADE,driver_id uuid REFERENCES users(id),lat numeric NOT NULL,lng numeric NOT NULL,accuracy numeric,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS invoices(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),invoice_number text UNIQUE NOT NULL,customer_id uuid REFERENCES customers(id),trip_id uuid REFERENCES trips(id),issue_date date DEFAULT current_date,due_date date,net numeric NOT NULL,vat_rate numeric NOT NULL,vat numeric NOT NULL,gross numeric NOT NULL,status text DEFAULT 'Open',description text,paid_at timestamptz);
CREATE TABLE IF NOT EXISTS audit_log(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,user_name text,role text,action text,details text,created_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_gps_trip_time ON gps_points(trip_id,created_at DESC);

CREATE TABLE IF NOT EXISTS calendar_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,description text,start_date date NOT NULL,start_time time,end_date date,end_time time,all_day boolean NOT NULL DEFAULT false,location text,event_type text NOT NULL DEFAULT 'Termin',created_by uuid REFERENCES users(id),created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_calendar_events_dates ON calendar_events(start_date,end_date);
